### ISSUE TITLE
cubemap generation crashes game and doesn't seemingly do anything?

### ISSUE THREAD

**Issue by ashifolfi** [BobbyShmurner/CubemapMaker#2] opened 2023-11-24 17:23 UTC
![image](https://github.com/BobbyShmurner/CubemapMaker/assets/29577987/a02c1445-377d-466b-92c8-634df76f9068)

self explanatory. I created a cubemap, and the game seemingly froze before encountering a full on crash afterwards

**Comment by ashifolfi** [comment] 2023-11-24 17:24
btw the generated cubemap is uh
completely empty. not entirely sure what caused this but I don't think that should be empty given where I was when it was taken

![image](https://github.com/BobbyShmurner/CubemapMaker/assets/29577987/344427ef-5fcf-4164-a5e0-abc9b96b9c4a)

**Comment by ashifolfi** [comment] 2023-11-24 17:31
Tried a second time making sure I hit the right key (f10) and yep.
![image](https://github.com/BobbyShmurner/CubemapMaker/assets/29577987/72ff8e4e-6f07-43f8-a895-2c8dc4fbeba6)
it's fully empty

**Comment by BobbyShmurner** [comment] 2024-02-22 21:52
Sorry for not responding sooner!

That is definitely odd...
I've pushed an update that fixed a different issue with the camera freezing, so maybe try and see if that fixed anything?

If not then I'll take a look at it

**Comment by BobbyShmurner** [comment] 2024-02-22 22:00
I'll close this for now since I'm unable to reproduce it, but if it still doesn't work, just leave a comment here
Thanks :D

**Closed as completed by BobbyShmurner** 2024-02-22 22:00 UTC
